os: linux
language: node_js
node_js:
  - "stable"

cache:
  yarn: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache
    # next.js build cache
    - web/.next/cache
    # node_modules
    - web/node_modules
    - fbg-server/node_modules

install:
  - yarn install

script:
  - yarn run ci

after_success:
  - cd web/ && yarn run test:coveralls
