version: '3.7'

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      SERVER_TYPE: 'WEB'
  bgio:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      SERVER_TYPE: 'BGIO'
  blog:
    build:
      context: blog
      dockerfile: Dockerfile
    ports:
      - '8080:80'
  backend:
    build:
      context: fbg-server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
